### ISSUE TITLE
Support Rails 6

### ISSUE THREAD

**Issue by w0113** [Ebbe/arask#1]
Hi,
first of all, thank you for your work with arask. I use it in a small Rails project and it works great!

I tried to upgrade my project to Rails 6, but when I tried to install the new gems I got an error that arask has a dependency on Rails 5. I changed the dependencies within the gemspec file and did a short test run within my application where everything worked fine with arask.

Would you consider changing the [gemspec](https://github.com/Ebbe/arask/blob/d8a44f5678c04195d04007099f193ed863582a00/arask.gemspec#L19) file to accept Rails ">= 5.0.0"?

**Comment by Ebbe** [comment]
Absolutely! I'll do that shortly.

PS. Sorry I didn't see your message before. I must have missed the notification :/

**Comment by Ebbe** [comment]
Done! :)

**Comment by w0113** [comment]
Thank you! Your work is very appreciated!
