### ISSUE TITLE
Arask makes Rails touch the database on asset:precompile for production

### ISSUE THREAD

**Issue by primeapple** [Ebbe/arask#15]
Ok, so I have the following issue:

When running
```sh
RAILS_ENV=production rake assets:precompile
```
normally Rails does not touch the database. This is important for example in docker, when the db is not yet set up in the building process. So using your gem breaks the typical docker building process.

However, using your gem it started to connect to the database (or at least go through the database.yml file which it doesnt do otherwise). This could also be because of some of your dependencies (however it seems you are not using any).

Do you have any ideas about this?

**Comment by Ebbe** [comment]
Sorry for the late reply.
I just tested this on a fresh install with rails 6.1.3. I don't have any errors when running assets precompile for production. I also tried in a docker to be sure.
Can you create an example I can recreate?

**Comment by Ebbe** [comment]
I've worked on initialization. Could you test with the new version 1.2.4?

**Comment by primeapple** [comment]
Hello,
I appreciate your reply! However it was a bit to late and I already fixed the issue by using cron instead.

So I'm sorry, I will not be able to help you with this. At least not for the next ~2 months.

On thing you could try is to make sure the database is NOT running, when running `RAILS_ENV=production rake assets:precompile` (also make sure you actually have any assets to compile, I used some JavaScript with Webpacker).  
This threw an error in my case.

**Comment by Ebbe** [comment]
I simply can't recreate it. Running in docker with no db with some javascript and webpack. No error.
I'll close it for now. If you find a way to recreate it or you stumple upon the error again, let me know.
