### ISSUE TITLE
Multiple cron jobs not running?

### ISSUE THREAD

**Issue by kurtpeniket** [Ebbe/arask#66]
Hi, thanks for creating this gem. Super helpful for me on a server I can't use a normal crontab on.

I am having an issue with a rake task that never seems to fire. I can log onto the server and manually kick off the rake task without issues so I'm guessing it's nothing to do with the actual task code.

To try and debug, I added another task that literally just logs the current time on the hour to see if _any_ jobs were being run:

```ruby
Arask.setup do |arask|
  if Rails.env.production?
    arask.create task: 'notifications:send_reminders', cron: '0 9 * * 4,0' 
    arask.create task: 'cron:test_task', cron: '0 * * * *' # logging task
  end
end
```

And I was reliably getting this in the rails logs, exactly as expected:

```
INFOI, [2024-06-02T07:00:00.000842 #113]  INFO -- : [ActiveJob] [Arask::RunJobs] [17741927-4c50-4566-8ff4-f1144644c71f] Performing Arask::RunJobs (Job ID: 17741927-4c50-4566-8ff4-f1144644c71f) from Async(default) enqueued at 2024-06-02T06:00:00Z
INFO Cron job is running. Current time: 2024-06-02 07:00:00 +0000
INFOI, [2024-06-02T07:00:00.146740 #113]  INFO -- : [ActiveJob] [Arask::RunJobs] [17741927-4c50-4566-8ff4-f1144644c71f] Cron job is running. Current time: 2024-06-02 07:00:00 +0000
INFOI, [2024-06-02T07:00:00.152043 #113]  INFO -- : [ActiveJob] [Arask::RunJobs] [17741927-4c50-4566-8ff4-f1144644c71f] Enqueued Arask::RunJobs (Job ID: 10fa8236-80b1-4a58-bd71-490e20d9d0f3) to Async(default) at 2024-06-02 08:00:00 UTC
INFOI, [2024-06-02T07:00:00.152364 #113]  INFO -- : [ActiveJob] [Arask::RunJobs] [17741927-4c50-4566-8ff4-f1144644c71f] Performed Arask::RunJobs (Job ID: 17741927-4c50-4566-8ff4-f1144644c71f) from Async(default) in 151.57ms
```
However, when the time comes to run both jobs(on the hour **and** at 9 on Thurs /Sun) all I get in the logs is this:

```
INFOI, [2024-06-02T09:00:00.000969 #120]  INFO -- : [ActiveJob] [Arask::RunJobs] [300bdcb2-6c02-4e54-85ee-7fdd8cd34404] Performing Arask::RunJobs (Job ID: 300bdcb2-6c02-4e54-85ee-7fdd8cd34404) from Async(default) enqueued at 2024-06-02T08:00:00Z
INFOI, [2024-06-02T09:00:00.061306 #120]  INFO -- : [ActiveJob] [Arask::RunJobs] [300bdcb2-6c02-4e54-85ee-7fdd8cd34404] Enqueued Arask::RunJobs (Job ID: acfd1047-ca7a-4d6a-a720-05dee62205c9) to Async(default) at 2024-06-02 10:00:00 UTC
INFOI, [2024-06-02T09:00:00.062680 #120]  INFO -- : [ActiveJob] [Arask::RunJobs] [300bdcb2-6c02-4e54-85ee-7fdd8cd34404] Performed Arask::RunJobs (Job ID: 300bdcb2-6c02-4e54-85ee-7fdd8cd34404) from Async(default) in 60.58ms
```

I looked at the `arask_jobs` table and both jobs are there with the correct data and being updated with the right `execute_at` fields.

Sorry if I'm making a dumb mistake somewhere but I can't think why this would be happening, any help or advice would be much appreciated 🙏🏻!

**Comment by kurtpeniket** [comment]
Update:

I tried removing the test job (so only one job is run) and simplifying the cron so that it just runs at 9 daily but I still just get:

```
I, [2024-06-09T09:00:00.000700 #121]  INFO -- : [ActiveJob] [Arask::RunJobs] [19049697-af4b-496e-b9fa-02af16dad5fb] Performing Arask::RunJobs (Job ID: 19049697-af4b-496e-b9fa-02af16dad5fb) from Async(default) enqueued at 2024-06-08T09:00:00Z
I, [2024-06-09T09:00:04.819341 #121]  INFO -- : [ActiveJob] [Arask::RunJobs] [19049697-af4b-496e-b9fa-02af16dad5fb] Enqueued Arask::RunJobs (Job ID: a1bbbc6f-3acb-4e83-b7de-2d53a243c484) to Async(default) at 2024-06-10 09:00:00 UTC
I, [2024-06-09T09:00:04.819489 #121]  INFO -- : [ActiveJob] [Arask::RunJobs] [19049697-af4b-496e-b9fa-02af16dad5fb] Performed Arask::RunJobs (Job ID: 19049697-af4b-496e-b9fa-02af16dad5fb) from Async(default) in 4818.85ms
```

The first line in the rake task just `puts` a string so that should be showing regardless of the actual code being run.

**Comment by Ebbe** [comment]
From here it certanly doesn't seem like you are doing anything wrong. The last example took almost 5 seconds. When running in production `puts` are not shown in logs.

**Comment by kurtpeniket** [comment]
> From here it certanly doesn't seem like you are doing anything wrong. Are you sure it isn't running? The last example took almost 5 seconds. When running in production `puts` are not shown in logs. Running multiple jobs at the same time does not necessarily mean more output. Arask "wakes up" and runs all pending tasks resulting in only one "cycle" of Arask logs.

Ah that makes sense, I'll keep trying to debug as it may just be an issue with my prod environment or it could be running but not logging anything. I mainly wanted to make sure I'd not made any obvious mistakes with the setup. Thanks @Ebbe !
